/*
 * OHS_text_const.h
 *
 *  Created on: Dec 8, 2020
 *      Author: vysocan
 */

#ifndef OHS_TEXT_CONST_H_
#define OHS_TEXT_CONST_H_

const char weekNumber[][7] = {
// 12345678901234567890
  "Last",
  "First",
  "Second",
  "Third",
  "Fourth"
};

const char weekDay[][10] = {
// 12345678901234567890
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday"
};

const char weekDayShort[][3] = {
  "Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"
};

const char monthName[][4] = {
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
};

const char durationSelect[][10] = {
// 12345678901234567890
  "second(s)",
  "minute(s)",
  "hour(s)",
  "day(s)"
};

#define TEXT_Get                      "Get"
#define TEXT_Set                      "Set"
#define TEXT_Help                     "Help"
#define TEXT_System                   "System"
#define TEXT_info                     "information"
#define TEXT_started                  "started"
#define TEXT_Undefined                "Undefined"
#define TEXT_removed                  "removed"
#define TEXT_disabled                 "disabled"
#define TEXT_address                  "address"
#define TEXT_unable                   "unable"
#define TEXT_to                       "to"
#define TEXT_Needed                   "Needed"
#define TEXT_resolve                  "resolve"
#define TEXT_Address                  "Address"
#define TEXT_Group                    "Group"
#define TEXT_group                    "group"
#define TEXT_registration             "registration"
#define TEXT_error                    "error"
#define TEXT_failure                  "failure"
#define TEXT_registered               "registered"
#define TEXT_is                       "is"
#define TEXT_Authentication           "Authentication"
#define TEXT_authentication           "authentication"
#define TEXT_disarming                "disarming"
#define TEXT_Sensor                   "Sensor"
#define TEXT_sensor                   "sensor"
#define TEXT_Input                    "Input"
#define TEXT_Output                   "Output"
#define TEXT_Siren                    "Siren"
#define TEXT_iButton                  "iButton"
#define TEXT_Temperature              "Temperature"
#define TEXT_temperature              "temperature"
#define TEXT_Humidity                 "Humidity"
#define TEXT_humidity                 "humidity"
#define TEXT_Pressure                 "Pressure"
#define TEXT_pressure                 "pressure"
#define TEXT_Voltage                  "Voltage"
#define TEXT_voltage                  "voltage"
#define TEXT_Battery                  "Battery"
#define TEXT_RTC                      "RTC"
#define TEXT_reset                    "reset"
#define TEXT_reason                   "reason"
#define TEXT_Digital                  "Digital"
#define TEXT_Analog                   "Analog"
#define TEXT_Float                    "Float"
#define TEXT_TX_Power                 "TX_Power"
#define TEXT_Gas                      "Gas"
#define TEXT_Illumination             "Illumination"
#define TEXT_illuminance              "illuminance"
#define TEXT_Fingerprint              "Fingerprint"
#define TEXT_not                      "not"
#define TEXT_None                     "None"
#define TEXT_Asterisk                 "*"
#define TEXT_authorized               "authorized"
#define TEXT_disconnected             "disconnected"
#define TEXT_connect                  "connect"
#define TEXT_timeout                  "timeout"
#define TEXT_refused                  "refused"
#define TEXT_server                   "server"
#define TEXT_protocol                 "protocol"
#define TEXT_version                  "version"
#define TEXT_identifier               "identifier"
#define TEXT_strength                 "strength"
#define TEXT_unknown                  "unknown"
#define TEXT_empty                    "empty"
#define TEXT_Empty                    "Empty"
#define TEXT_roaming                  "roaming"
#define TEXT_searching                "searching"
#define TEXT_network                  "network"
#define TEXT_denied                   "denied"
#define TEXT_cosp                     ", "
#define TEXT_Modem                    "Modem"
#define TEXT_On                       "On"
#define TEXT_Off                      "Off"
#define TEXT_1                        "1"
#define TEXT_2                        "2"
#define TEXT_3                        "3"
#define TEXT_4                        "4"
#define TEXT_0x                       "0x"
#define TEXT_1x                       "1x"
#define TEXT_2x                       "2x"
#define TEXT_3x                       "3x"
#define TEXT_power                    "power"
#define TEXT_watchdog                 "watchdog"
#define TEXT_independent              "independent"
#define TEXT_software                 "software"
#define TEXT_power_on                 "power-on"
#define TEXT_brown_out                "brown-out"
#define TEXT_main                     "main"
#define TEXT_monitoring               "monitoring"
#define TEXT_Node                     "Node"
#define TEXT_Name                     "Name"
#define TEXT_name                     "name"
#define TEXT_MQTT                     "MQTT"
#define TEXT_HA                       "HA"
#define TEXT_HAD                      "HAD"
#define TEXT_Function                 "Function"
#define TEXT_Type                     "Type"
#define TEXT_type                     "type"
#define TEXT_publish                  "publish"
#define TEXT_callback                 "callback"
#define TEXT_subscribe                "subscribe"
#define TEXT_semaphore                "semaphore"
#define TEXT_Subscribe                "Subscribe"
#define TEXT_Last                     "Last"
#define TEXT_devation                 "deviation"
#define TEXT_message                  "message"
#define TEXT_Queued                   "Queued"
#define TEXT_Value                    "Value"
#define TEXT_Number                   "Number"
#define TEXT_Email                    "Email"
#define TEXT_Global                   "Global"
#define TEXT_Home                     "Home"
#define TEXT_Assistant                "Assistant"
#define TEXT_Discovery                "Discovery"
#define TEXT_Contact                  "Contact"
#define TEXT_contact                  "contact"
#define TEXT_User                     "User"
#define TEXT_all                      "all"
#define TEXT_Key                      "Key"
#define TEXT_Open                     "Open"
#define TEXT_alarm                    "alarm"
#define TEXT_Alarm                    "Alarm"
#define TEXT_as                       "as"
#define TEXT_As                       "As"
#define TEXT_tamper                   "tamper"
#define TEXT_tampered                 "tampered"
#define TEXT_Delay                    "Delay"
#define TEXT_OK                       "OK"
#define TEXT_Status                   "Status"
#define TEXT_remote                   "remote"
#define TEXT_local                    "local"
#define TEXT_battery                  "battery"
#define TEXT_analog                   "analog"
#define TEXT_digital                  "digital"
#define TEXT_Zone                     "Zone"
#define TEXT_zone                     "zone"
#define TEXT_refresh                  "refresh"
#define TEXT_rejected                 "rejected"
#define TEXT_delay                    "delay"
#define TEXT_SMS                      "SMS"
#define TEXT_sms                      "sms"
#define TEXT_Page                     "Page"
#define TEXT_disarmed                 "disarmed"
#define TEXT_pending                  "pending"
#define TEXT_armed                    "armed"
#define TEXT_auto                     "auto"
#define TEXT_open                     "open"
#define TEXT_allowed                  "allowed"
#define TEXT_matched                  "matched"
#define TEXT_re                       "re"
#define TEXT_Date                     "Date"
#define TEXT_Entry                    "Entry"
#define TEXT_Alert                    "Alert"
#define TEXT_test                     "test"
#define TEXT_key                      "key"
#define TEXT_value                    "value"
#define TEXT_once                     "once"
#define TEXT_after                    "after"
#define TEXT_always                   "always"
#define TEXT_constant                 "constant"
#define TEXT_connected                "connected"
#define TEXT_Connected                "Connected"
#define TEXT_Armed                    "Armed"
#define TEXT_Arm                      "Arm"
#define TEXT_arm                      "arm"
#define TEXT_arm_home                 "arm_home"
#define TEXT_arm_away                 "arm_away"
#define TEXT_disarm                   "disarm"
#define TEXT_arming                   "arming"
#define TEXT_Disarm                   "Disarm"
#define TEXT_chain                    "chain"
#define TEXT_trigger                  "trigger"
#define TEXT_triggered                "triggered"
#define TEXT_Trigger                  "Trigger"
#define TEXT_Auto                     "Auto"
#define TEXT_Tamper                   "Tamper"
#define TEXT_relay                    "relay"
#define TEXT_home                     "home"
#define TEXT_away                     "away"
#define TEXT_Time                     "Time"
#define TEXT_time                     "time"
#define TEXT_Start                    "Start"
#define TEXT_Up                       "Up"
#define TEXT_AC                       "AC"
#define TEXT_Register                 "Register"
#define TEXT_Signal                   "Signal"
#define TEXT_Alive                    "Alive"
#define TEXT_Admin                    "Admin"
#define TEXT_user                     "user"
#define TEXT_Password                 "Password"
#define TEXT_password                 "password"
#define TEXT_SMTP                     "SMTP"
#define TEXT_NTP                      "NTP"
#define TEXT_Radio                    "Radio"
#define TEXT_Frequency                "Frequency"
#define TEXT_Server                   "Server"
#define TEXT_port                     "port"
#define TEXT_of                       "of"
#define TEXT_at                       "at"
#define TEXT_offset                   "offset"
#define TEXT_end                      "end"
#define TEXT_start                    "start"
#define TEXT_DS                       "Daylight saving"
#define TEXT_Standard                 "Standard"
#define TEXT_format                   "format"
#define TEXT_oclock                   "o'clock"
#define TEXT_Balanced                 "Balanced"
#define TEXT_balanced                 "balanced"
#define TEXT_low                      "low"
#define TEXT_state                    "state"
#define TEXT_binary_sensor            "binary_sensor"
#define TEXT_alarm_control_panel      "alarm_control_panel"
#define TEXT_State                    "State"
#define TEXT_Blocks                   "Blocks"
#define TEXT_Entries                  "Entries"
#define TEXT_Used                     "Used"
#define TEXT_Free                     "Free"
#define TEXT_Total                    "Total"
#define TEXT_Metric                   "Metric"
#define TEXT_Hash                     "Hash"
#define TEXT_Period                   "Period"
#define TEXT_Run                      "Run"
#define TEXT_Script                   "Script"
#define TEXT_Next                     "Next"
#define TEXT_on                       "on"
#define TEXT_off                      "off"
#define TEXT_Calendar                 "Calendar"
#define TEXT_Duration                 "Duration"
#define TEXT_duration                 "duration"
#define TEXT_Timer                    "Timer"
#define TEXT_timer                    "timer"
#define TEXT_kB                       "kB"
#define TEXT_Heap                     "Heap"
#define TEXT_heap                     "heap"
#define TEXT_Storage                  "Storage"
#define TEXT_storage                  "storage"
#define TEXT_Fragmentation            "Fragmentation"
#define TEXT_Evaluate                 "Evaluate"
#define TEXT_script                   "script"
#define TEXT_Result                   "Result"
#define TEXT_linked_to                "linked to"
#define TEXT_Condition                "Condition"
#define TEXT_Hysteresis               "Hysteresis"
#define TEXT_Pass                     "Pass"
#define TEXT_To                       "To"
#define TEXT_queue                    "queue"
#define TEXT_full                     "full"
#define TEXT_Registration             "Registration"
#define TEXT_not_found                "not found"
#define TEXT_activated                "activated"
#define TEXT_error_free               "Not enough free space in "
#define TEXT_error_rename             "Unable to rename"
#define TEXT_error_name_empty         "Name cannot be empty"
#define TEXT_error_script_not_found   "Script not found"

#endif /* OHS_TEXT_CONST_H_ */
